{
  "openapi": "3.0.0",
  "info": {
    "title": "KoolKatsAPI",
    "version": "1.0",
    "contact": {
      "name": "Peri Telemachou",
      "email": "z5214738@ad.unsw.edu.au"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/users": {
      "parameters": [],
      "get": {
        "summary": "Get User Info by User ID",
        "tags": [],
        "responses": {
          "200": {
            "description": "User Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Get User Alice Smith": {
                    "value": {
                      "id": 142,
                      "firstName": "Alice",
                      "lastName": "Smith",
                      "email": "alice.smith@gmail.com",
                      "dateOfBirth": "1997-10-31",
                      "emailVerified": true,
                      "signUpDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          }
        },
        "operationId": "get-users-userId",
        "description": "Retrieve the information of the user with the matching user ID.",
        "parameters": []
      },
      "patch": {
        "summary": "Update User Information",
        "operationId": "patch-users-userId",
        "responses": {
          "200": {
            "description": "User Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Updated User Rebecca Baker": {
                    "value": {
                      "id": 13,
                      "firstName": "Rebecca",
                      "lastName": "Baker",
                      "email": "rebecca@gmail.com",
                      "dateOfBirth": "1985-10-02",
                      "emailVerified": false,
                      "createDate": "2019-08-24"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "User Not Found"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "description": "Update the infromation of an existing user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string",
                    "description": "If a new email is given, the user's email verified property will be set to false."
                  },
                  "dateOfBirth": {
                    "type": "string"
                  }
                }
              },
              "examples": {
                "Update First Name": {
                  "value": {
                    "firstName": "Rebecca"
                  }
                },
                "Update Email": {
                  "value": {
                    "email": "rebecca@gmail.com"
                  }
                },
                "Update Last Name & Date of Birth": {
                  "value": {
                    "lastName": "Baker",
                    "dateOfBirth": "1985-10-02"
                  }
                }
              }
            }
          },
          "description": "Patch user properties to update."
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query"
          }
        ]
      }
    },
    "/user": {
      "post": {
        "summary": "Create New User",
        "operationId": "post-user",
        "responses": {
          "200": {
            "description": "User Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "New User Bob Fellow": {
                    "value": {
                      "id": 12,
                      "firstName": "Bob",
                      "lastName": "Fellow",
                      "email": "bob.fellow@gmail.com",
                      "dateOfBirth": "1996-08-24",
                      "emailVerified": false,
                      "createDate": "2020-11-18"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing Required Information"
          },
          "409": {
            "description": "Email Already Taken"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "firstName": {
                    "type": "string"
                  },
                  "lastName": {
                    "type": "string"
                  },
                  "email": {
                    "type": "string"
                  },
                  "dateOfBirth": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "dateOfBirth"
                ]
              },
              "examples": {
                "Create User Bob Fellow": {
                  "value": {
                    "firstName": "Bob",
                    "lastName": "Fellow",
                    "email": "bob.fellow@gmail.com",
                    "dateOfBirth": "1996-08-24"
                  }
                }
              }
            }
          },
          "description": "Post the necessary fields for the API to create a new user."
        },
        "description": "Create a new user."
      }
    }
  },
  "components": {
    "schemas": {
      "Article": {
        "title": "Article",
        "type": "object",
        "description": "",
        "x-examples": {
          "Example": {
            "title": "First COVID Case in Sydney",
            "url": "https://fakenews.com.au/first-covid-case-sydney",
            "location": "Sydney",
            "startDate": "user@example.com",
            "endDate": "1997-10-31",
            "cases": 0
          }
        },
        "properties": {
          "headline": {
            "description": "Unique identifier for the given user.",
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "location": {
            "$ref": "#/components/schemas/Location"
          },
          "reports": {
            "type": "array",
            "description": "Set to true if the user's email has been verified.",
            "items": {
              "$ref": "#/components/schemas/Report"
            }
          },
          "termsFound": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "main_text": {
            "type": "string"
          },
          "date_of_publication": {
            "$ref": "#/components/schemas/Dates"
          }
        },
        "required": [
          "headline",
          "url",
          "location",
          "reports"
        ]
      },
      "UserInput": {
        "title": "UserInput",
        "type": "object",
        "x-examples": {
          "SydneyRequest": {
            "startDate": "2019-01-11T09:02:00",
            "endDate": "2019-01-16T11:02:10",
            "keyTerms": "anthrax,zika",
            "location": "Sydney"
          }
        },
        "properties": {
          "startDate": {
            "type": "string",
            "example": "YYYY-MM-DDtHH:MM:SS"
          },
          "endDate": {
            "type": "string",
            "example": "YYYY-MM-DDtHH:MM:SS"
          },
          "keyTerms": {
            "type": "string"
          },
          "location": {
            "type": "string"
          }
        },
        "required": [
          "startDate",
          "endDate",
          "keyTerms",
          "location"
        ]
      },
      "Report": {
        "title": "Report",
        "type": "object",
        "x-examples": {
          "Example": {
            "diseases": [
              "COVID",
              "Malaria"
            ],
            "syndromes": [],
            "event_date": "2019-05-05T11:22:01",
            "locations": [
              "Sydney",
              "Melbourne",
              "Perth"
            ]
          }
        },
        "properties": {
          "diseases": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Disease"
            }
          },
          "syndromes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Syndrome"
            }
          },
          "event_date": {
            "$ref": "#/components/schemas/Dates"
          },
          "locations": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Location"
            }
          }
        },
        "required": [
          "event_date"
        ]
      },
      "Dates": {
        "title": "Dates",
        "oneOf": [
          {
            "$ref": "#/components/schemas/DateExact"
          },
          {
            "$ref": "#/components/schemas/DateRange"
          }
        ]
      },
      "DateRange": {
        "type": "string",
        "title": "DateRange",
        "pattern": "^(\\d{4})-(\\d\\d|xx)-(\\d\\d|xx) (\\d\\d|xx):(\\d\\d|xx):(\\d\\d|xx) to (\\d{4})-(\\d\\d|xx)-(\\d\\d|xx) (\\d\\d|xx):(\\d\\d|xx):(\\d\\d|xx)$"
      },
      "DateExact": {
        "type": "string",
        "title": "DateExact",
        "x-examples": {
          "example-1": "string"
        },
        "pattern": "^(\\d{4})-(\\d\\d|xx)-(\\d\\d|xx) (\\d\\d|xx):(\\d\\d|xx):(\\d\\d|xx)$"
      },
      "Disease": {
        "title": "Disease",
        "type": "string"
      },
      "Syndrome": {
        "title": "Syndrome",
        "type": "string"
      },
      "Location": {
        "title": "Location",
        "type": "object",
        "properties": {
          "country": {
            "type": "string"
          },
          "location": {
            "type": "string"
          }
        }
      },
      "EventType": {
        "title": "EventType",
        "type": "string"
      }
    },
    "responses": {
      "ArticleList": {
        "description": "Example response",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "articles": {
                  "$ref": "#/components/schemas/Article"
                },
                "debugInfo": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "accessTime": {
                      "type": "number"
                    },
                    "serviceTime": {
                      "type": "number"
                    }
                  }
                }
              },
              "required": [
                "articles"
              ]
            }
          }
        }
      }
    },
    "parameters": {
      "periodOfInterest": {
        "name": "periodOfInterest",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        },
        "description": "Either a single date or date range"
      },
      "location": {
        "name": "location",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        },
        "description": "The city or country of interest"
      },
      "keyTerms": {
        "name": "keyTerms",
        "in": "query",
        "required": false,
        "schema": {
          "type": "array"
        },
        "description": "Words to filter the search"
      }
    }
  }
}