{
  "openapi": "3.0.0",
  "info": {
    "title": "KoolKatsAPI",
    "version": "1.0",
    "contact": {
      "name": "Peri Telemachou",
      "email": "z5214738@ad.unsw.edu.au"
    },
    "description": "Our data is scraped from the WHO website.\n\nWe plan to update the data everyday at 6am. Depending on when API requests are sent, it may not be the most updated version. "
  },
  "servers": [
    {
      "url": "http://52.87.94.130:5000"
    }
  ],
  "paths": {
    "/disease": {
      "parameters": [],
      "get": {
        "summary": "Get Disease",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "disease": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "cases": {
                            "type": "integer"
                          },
                          "occurrences": {
                            "type": "integer"
                          }
                        }
                      }
                    },
                    "totalArticles": {
                      "type": "integer"
                    },
                    "debugInfo": {
                      "$ref": "#/components/schemas/DebugInfo"
                    }
                  }
                },
                "examples": {
                  "example": {
                    "value": {
                      "debugInfo": {
                        "name": "KoolKats",
                        "accessTime": "2021-03-22 08:55:20.535835",
                        "serviceTime": "0:00:00.042005",
                        "dataSource": "WHO"
                      },
                      "diseases": [
                        {
                          "name": "yellow fever",
                          "cases": 136454,
                          "occurrences": 19
                        },
                        {
                          "name": "chikungunya",
                          "cases": 5880,
                          "occurrences": 11
                        }
                      ],
                      "totalArticles": 324
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-disease-info",
        "description": "Gets the number of cases and number of articles mentioning 1 or more diseases within a date range.",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "2005-01-01T00:00:00"
            },
            "in": "query",
            "name": "startDate",
            "description": "The desired starting date to fetch articles for in the form 'YYYY-MM-DDTHH:MM:SS'",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "2021-01-01T00:00:00"
            },
            "in": "query",
            "name": "endDate",
            "description": "The desired end date to fetch articles for in the form 'YYYY-MM-DDTHH:MM:SS'",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "yellow fever, chikungunya"
            },
            "in": "query",
            "name": "keyTerms",
            "description": "Words to filter the search e.g. \"listeriosis\", \"yellow fever\", \"cholera\", \"haemorrhagic fever syndrome\", \"acute watery diarrhoeal syndrome\", \"leishmaniasis\", \"dengue fever\", \"influenza\", \"acute respiratory syndrome\", \"measles\", \"staphylococcal food intoxication\", \"lassa fever\", \"meningococcal disease\", \"leptospirosis\", \"rift valley fever\",  \"middle east respiratory syndrome coronavirus (mers-cov)\", \"monkeypox\", \"ebola virus disease\", \"chikungunya\", \"gonococcal infection\", \"hantavirus pulmonary syndrome\", \"poliomyelitis\", \"hepatitis\", \"oropouche virus disease\", \"novel coronavirus\", \"typhoid fever\", \"nipah virus\", \"plague\", \"myocarditis\", \"anthrax\", \"rabies\", \"legionellosis\",  \"enterovirus\",  \"malaria\", \"crimean-congo haemorrhagic fever\", \"dengue haemorrhagic fever\", \"legionnaires\",  \"west nile fever\",  \"relapsing fever\", \"coccidioidomycosis\", \"acute neurological syndrome\", \"shigellosis\",  \"marburg haemorrhagic fever\", \"japanese encephalitis\",  \"botulism\"",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "France"
            },
            "in": "query",
            "name": "location",
            "description": "The country of interest"
          }
        ]
      }
    },
    "/occurrences": {
      "parameters": [],
      "get": {
        "summary": "Get Occurrences",
        "operationId": "get-occurrences-by-location",
        "description": "Gets the number of articles mentioning 1 or more diseases by location",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "yellow fever, cholera"
            },
            "in": "query",
            "name": "keyTerms",
            "required": true,
            "description": "Words to filter the search e.g. \"listeriosis\", \"yellow fever\", \"cholera\", \"haemorrhagic fever syndrome\", \"acute watery diarrhoeal syndrome\", \"leishmaniasis\", \"dengue fever\", \"influenza\", \"acute respiratory syndrome\", \"measles\", \"staphylococcal food intoxication\", \"lassa fever\", \"meningococcal disease\", \"leptospirosis\", \"rift valley fever\",  \"middle east respiratory syndrome coronavirus (mers-cov)\", \"monkeypox\", \"ebola virus disease\", \"chikungunya\", \"gonococcal infection\", \"hantavirus pulmonary syndrome\", \"poliomyelitis\", \"hepatitis\", \"oropouche virus disease\", \"novel coronavirus\", \"typhoid fever\", \"nipah virus\", \"plague\", \"myocarditis\", \"anthrax\", \"rabies\", \"legionellosis\",  \"enterovirus\",  \"malaria\", \"crimean-congo haemorrhagic fever\", \"dengue haemorrhagic fever\", \"legionnaires\",  \"west nile fever\",  \"relapsing fever\", \"coccidioidomycosis\", \"acute neurological syndrome\", \"shigellosis\",  \"marburg haemorrhagic fever\", \"japanese encephalitis\",  \"botulism\""
          },
          {
            "schema": {
              "type": "string",
              "example": "2005-01-01T00:00:00"
            },
            "in": "query",
            "name": "startDate",
            "description": "The desired starting date to fetch articles for in the form 'YYYY-MM-DDTHH:MM:SS'"
          },
          {
            "schema": {
              "type": "string",
              "example": "2021-01-01T00:00:00"
            },
            "in": "query",
            "name": "endDate",
            "description": "The desired end date to fetch articles for in the form 'YYYY-MM-DDTHH:MM:SS'"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "locations": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "disease": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "occurrences": {
                            "type": "integer"
                          }
                        }
                      }
                    },
                    "debugInfo": {
                      "$ref": "#/components/schemas/DebugInfo"
                    }
                  }
                },
                "examples": {
                  "example": {
                    "value": {
                      "locations": [
                        {
                          "disease": "Yellow Fever",
                          "name": "Democratic Republic of Congo",
                          "occurrences": 2
                        },
                        {
                          "disease": "Yellow Fever",
                          "name": "Islamic Republic of Pakistan",
                          "occurrences": 1
                        },
                        {
                          "disease": "Yellow Fever",
                          "name": "Haiti",
                          "occurrences": 1
                        },
                        {
                          "disease": "Yellow Fever",
                          "name": "Uganda",
                          "occurrences": 1
                        }
                      ],
                      "debugInfo": {
                        "name": "KoolKats",
                        "accessTime": "2021-03-19 04:44:22.416770",
                        "serviceTime": "0:00:00.042005",
                        "dataSource": "WHO"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/articles": {
      "get": {
        "summary": "Get Articles",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "articles": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Article"
                      }
                    },
                    "debugInfo": {
                      "$ref": "#/components/schemas/DebugInfo"
                    }
                  }
                },
                "examples": {
                  "Example": {
                    "value": {
                      "debugInfo": {
                        "name": "KoolKats",
                        "accessTime": "2021-03-19 04:44:22.416770",
                        "serviceTime": "0:00:00.042005",
                        "dataSource": "WHO"
                      },
                      "articles": [
                        {
                          "date_of_publication": "2009-04-24 00:00:00",
                          "headline": "",
                          "location": "Mexico",
                          "main_text": "The United States Government has reported seven confirmed human cases of Swine Influenza A/H1N1 in the USA (five in California and two in Texas) and nine suspect cases. All seven confirmed cases had mild Influenza-Like Illness (ILI), with only one requiring brief hospitalization. No deaths have been reported.\nThe Government of Mexico has reported three separate events. In the Federal District of Mexico, surveillance began picking up cases of ILI starting 18 March. The number of cases has risen steadily through April and as of 23 April there are now more than 854 cases of pneumonia from the capital. Of those, 59 have died. In San Luis Potosi, in central Mexico, 24 cases of ILI, with three deaths, have been reported. And from Mexicali, near the border with the United States, four cases of ILI, with no deaths, have been reported.\nOf the Mexican cases, 18 have been laboratory confirmed in Canada as Swine Influenza A/H1N1, while 12 of those are genetically identical to the Swine Influenza A/H1N1 viruses from California.\nThe majority of these cases have occurred in otherwise healthy young adults. Influenza normally affects the very young and the very old, but these age groups have not been heavily affected in Mexico.\nBecause there are human cases associated with an animal influenza virus, and because of the geographical spread of multiple community outbreaks, plus the somewhat unusual age groups affected, these events are of high concern.\nThe Swine Influenza A/H1N1 viruses characterized in this outbreak have not been previously detected in pigs or humans. The viruses so far characterized have been sensitive to oseltamivir, but resistant to both amantadine and rimantadine.\nThe World Health Organization has been in constant contact with the health authorities in the United States, Mexico and Canada in order to better understand the risk which these ILI events pose. WHO (and PAHO) is sending missions of experts to Mexico to work with health authorities there. It is helping its Member States to increase field epidemiology activities, laboratory diagnosis and clinical management. Moreover, WHO's partners in the Global Alert and Response Network have been alerted and are ready to assist as requested by the Member States.\nWHO acknowledges the United States and Mexico for their proactive reporting and their collaboration with WHO and will continue to work with Member States to further characterize the outbreak.",
                          "reports": [],
                          "termFound": "influenza",
                          "url": "https://www.who.int/csr/don/2009_04_24/en/"
                        },
                        {
                          "date_of_publication": "2013-10-19 00:00:00",
                          "headline": "",
                          "location": "Mexico",
                          "main_text": "Disease outbreak news\nThe Ministry of Health in Mexico has reported 171 confirmed cases, including one death, of infection with Vibrio cholerae O1 Ogawa toxigenic between 9 September to 18 October 2013.\nIn the second week of September 2013, Mexico was affected simultaneously by a hurricane and tropical storm which caused heavy rains, floods, landslides and internal displacement of populations, thus increasing the risk of diarrhoeal diseases.\nOf the 171 confirmed cases, two are from the Federal District, 157 cases from the state of Hidalgo, nine from the state of Mexico, one from the state of San Luis Potosi and two from the state of Veracruz.\nEighty-six of the total confirmed cases are women and 85 are men with ages ranging from three months to 88 years old. Of these, thirty-nine cases were hospitalised.\nThe health authorities of Mexico continue to strengthen the outbreak investigation and surveillance at the national level and ensure the availability and quality care in medical units. Health professionals at different levels of the health care system are being trained about prevention, treatment and control of the disease. Measures are implemented to ensure access to drinking water and basic sanitation at the community level. Awareness campaigns, particularly around safe water and food consumption is being carried out in Spanish and indigenous languages.\nThis is the first local transmission of cholera recorded since the 1991-2001 cholera epidemic in Mexico. The genetic profile of the bacterium obtained from patients in Mexico presents high similarity (95 percent) with the strain that is currently circulating in three Caribbean countries (Haiti, Dominican Republic and Cuba), and is different from the strain that had been circulating in Mexico during 1991-2001 epidemic.\nWHO does not recommend that any travel or trade restrictions be applied to Mexico with respect to this event.",
                          "reports": [],
                          "termFound": "cholera",
                          "url": "https://www.who.int/csr/don/2013_10_19_cholera/en/"
                        },
                        {
                          "date_of_publication": "2013-10-28 00:00:00",
                          "headline": "",
                          "location": "Mexico",
                          "main_text": "Disease outbreak news\nThe Ministry of Health in Mexico has reported an additional five cases of infection with Vibrio cholerae O1 Ogawa toxigenic.\nThe five cases occurred in the geographic zone of la Huasteca, an area where urbanization, availability of drinking water and basic sanitation services are limited.\nFrom 9 September to date, a total of 176 confirmed cases, including one death, of infection with Vibrio cholerae O1 Ogawa toxigenic has been reported in the country. Of these, two are from the Federal District, 157 cases from the state of Hidalgo, nine from the state of Mexico, two from the state of San Luis Potosi and six from the state of Veracruz. Eighty-nine of the total confirmed cases are women and 87 are men. Fifty-seven cases have been hospitalized.\nAn antimicrobial susceptibility test for Vibrio cholerae O1 Ogawa toxigenic was conducted by the Institute of Epidemiological Diagnostics and Reference (InDRE) which demonstrated that the bacterium was susceptible to the medicines doxycycline and chloramphenicol, with reduced susceptibility to ciprofloxacin and resistance to trimethoprim/sulfamethoxazole.\nThe health authorities of Mexico continue to strengthen outbreak investigation and surveillance at the national level and continue to ensure the availability and quality of care in medical units. Health professionals at different levels of the health care system are being trained in prevention, treatment and control of the disease. Measures are being implemented to ensure access to drinking water and basic sanitation at the community level. Awareness campaigns, particularly around safe water and food consumption are being carried out in Spanish and indigenous languages.\nThis is the first local transmission of cholera recorded since the 1991-2001 cholera epidemic in Mexico. The genetic profile of the bacterium obtained from patients in Mexico presents high similarity (95%) with the strain that is currently circulating in three Caribbean countries (Haiti, Dominican Republic and Cuba), and is different from the strain that had been circulating in Mexico during 1991-2001 epidemic.\nWHO does not recommend that any travel or trade restrictions be applied to Mexico with respect to this event.",
                          "reports": [],
                          "termFound": "cholera",
                          "url": "https://www.who.int/csr/don/2013_10_28/en/"
                        },
                        {
                          "date_of_publication": "2013-11-13 00:00:00",
                          "headline": "",
                          "location": "Mexico",
                          "main_text": "Disease outbreak news\nThe Ministry of Health in Mexico has reported an additional four cases of infection with Vibrio cholerae O1 Ogawa. Of these, two are from the state of Hidalgo and two from the state of Veracruz.\nSince the beginning of this outbreak in September 2013 to date, a total of 180 confirmed cases, including one death, of cholera due to Vibrio cholerae O1 Ogawa has been reported in the country. Of these, two are from the Federal District, 159 cases from the state of Hidalgo, nine from the state of Mexico, two from the state of San Luis Potosi and eight from the state of Veracruz. Ninety-two of the total confirmed cases are women and 88 are men, with the age ranging from three-months to 88 years old.\nThe health authorities of Mexico continue to strengthen outbreak investigation and surveillance at the national level and continue to ensure the availability and quality of care in medical units. Health professionals at different levels of the health care system are being trained in prevention and treatment of the disease. Measures are being implemented to ensure access to drinking water and basic sanitation at the community level. Awareness campaigns, particularly around safe water and food consumption are being carried out in Spanish and indigenous languages.\nAn antimicrobial susceptibility test for Vibrio cholerae O1 Ogawa was conducted by the Institute of Epidemiological Diagnostics and Reference (InDRE) which demonstrated that the bacterium was susceptible to doxycycline and chloramphenicol, with reduced susceptibility to ciprofloxacin and resistance to trimethoprim/sulfamethoxazole.\nThis is the first local transmission of cholera recorded since the 1991-2001 cholera epidemic in Mexico. The genetic profile of the bacterium obtained from patients in Mexico presents high similarity (95%) with the strain that is currently circulating in three Caribbean countries (Haiti, Dominican Republic and Cuba), and is different from the strain that had been circulating in Mexico during 1991-2001 epidemic.\nWHO does not recommend that any travel or trade restrictions be applied to Mexico with respect to this event.",
                          "reports": [],
                          "termFound": "cholera",
                          "url": "https://www.who.int/csr/don/2013_11_13/en/"
                        },
                        {
                          "date_of_publication": "2013-11-25 00:00:00",
                          "headline": "",
                          "location": "Mexico",
                          "main_text": "Disease outbreak news\nThe Ministry of Health in Mexico has reported an additional four cases of infection with Vibrio cholerae O1 Ogawa. Of these, three are from the state of Veracruz and one from the state of Hidalgo.\nSince the beginning of this outbreak in September 2013 to date, a total of 184 confirmed cases, including one death, of cholera due to Vibrio cholerae O1 Ogawa has been reported in the country. Of these, 160 cases from the state of Hidalgo, 11 from the state of Veracruz, nine from the state of Mexico, two are from the Federal District, and two from the state of San Luis Potosi.\nThe health authorities of Mexico continue to strengthen surveillance and to ensure the availability and quality of care in medical units.\nMeasures are being implemented to ensure access to drinking water and basic sanitation at the community level. Awareness campaigns, particularly around safe water and food consumption are being carried out in Spanish and indigenous languages. Health professionals at different levels of the health care system are being trained in prevention and treatment of the disease.\nAn antimicrobial susceptibility test for Vibrio cholerae O1 Ogawa was conducted by the Institute of Epidemiological Diagnostics and Reference (InDRE) which demonstrated that the bacterium was susceptible to doxycycline and chloramphenicol, with reduced susceptibility to ciprofloxacin and resistance to trimethoprim/sulfamethoxazole.\nThis is the first local transmission of cholera recorded since 2001 in Mexico. The genetic profile of the bacterium obtained from patients in Mexico presents high similarity (95%) with the strain that is currently circulating in three Caribbean countries (Haiti, Dominican Republic and Cuba), and is different from the strain that had been circulating in Mexico during 1991-2001.\nWHO does not recommend that any travel or trade restrictions be applied to Mexico with respect to this event.",
                          "reports": [],
                          "termFound": "cholera",
                          "url": "https://www.who.int/csr/don/2013_11_25/en/"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-getArticles",
        "description": "Gets all articles from scraped World Health Organisation (WHO) source filtered by date range, location and key terms.",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "example": "influenza, cholera",
              "format": "Disease"
            },
            "in": "query",
            "name": "keyTerms",
            "description": "Words to filter the search e.g. \"listeriosis\", \"yellow fever\", \"cholera\", \"haemorrhagic fever syndrome\", \"acute watery diarrhoeal syndrome\", \"leishmaniasis\", \"dengue fever\", \"influenza\", \"acute respiratory syndrome\", \"measles\", \"staphylococcal food intoxication\", \"lassa fever\", \"meningococcal disease\", \"leptospirosis\", \"rift valley fever\",  \"middle east respiratory syndrome coronavirus (mers-cov)\", \"monkeypox\", \"ebola virus disease\", \"chikungunya\", \"gonococcal infection\", \"hantavirus pulmonary syndrome\", \"poliomyelitis\", \"hepatitis\", \"oropouche virus disease\", \"novel coronavirus\", \"typhoid fever\", \"nipah virus\", \"plague\", \"myocarditis\", \"anthrax\", \"rabies\", \"legionellosis\",  \"enterovirus\",  \"malaria\", \"crimean-congo haemorrhagic fever\", \"dengue haemorrhagic fever\", \"legionnaires\",  \"west nile fever\",  \"relapsing fever\", \"coccidioidomycosis\", \"acute neurological syndrome\", \"shigellosis\",  \"marburg haemorrhagic fever\", \"japanese encephalitis\",  \"botulism\"",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "Mexico"
            },
            "in": "query",
            "name": "location",
            "description": "The country of interest",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "2005-01-01T00:00:00"
            },
            "in": "query",
            "name": "startDate",
            "description": "The desired starting date to fetch articles for in the form 'YYYY-MM-DDTHH:MM:SS'",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "2021-01-01T00:00:00"
            },
            "in": "query",
            "name": "endDate",
            "description": "The desired end date to fetch articles for in the form 'YYYY-MM-DDTHH:MM:SS'",
            "required": true
          }
        ]
      },
      "parameters": []
    },
    "/popularDiseases": {
      "get": {
        "summary": "Get Popular Diseases",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "rankings": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Occurrences"
                      }
                    },
                    "debugInfo": {
                      "$ref": "#/components/schemas/DebugInfo"
                    }
                  }
                },
                "examples": {
                  "example": {
                    "value": {
                      "rankings": [
                        {
                          "name": "Influenza A",
                          "occurrences": 3
                        },
                        {
                          "name": "Ebola virus disease",
                          "occurrences": 2
                        },
                        {
                          "name": "Cholera",
                          "occurrences": 1
                        },
                        {
                          "name": "Rift Valley fever",
                          "occurrences": 1
                        },
                        {
                          "name": "MERS-CoV",
                          "occurrences": 1
                        }
                      ],
                      "debugInfo": {
                        "name": "KoolKats",
                        "accessTime": "2021-03-19 04:44:22.416770",
                        "serviceTime": "0:00:00.042005",
                        "dataSource": "WHO"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-popular-diseases",
        "description": "Gets the rankings of all diseases by the highest number of occurences in articles, can be filtered by location.",
        "parameters": [
          {
            "$ref": "#/components/parameters/numDiseases"
          },
          {
            "schema": {
              "type": "string",
              "example": "2005-01-01T00:00:00"
            },
            "in": "query",
            "name": "startDate",
            "description": "The desired starting date to fetch articles for in the form 'YYYY-MM-DDTHH:MM:SS'",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "2021-01-10T00:00:00"
            },
            "in": "query",
            "name": "endDate",
            "description": "The desired end date to fetch articles for in the form 'YYYY-MM-DDTHH:MM:SS'",
            "required": true
          },
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "location",
            "description": "The country of interest"
          }
        ]
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "Article": {
        "title": "Article",
        "type": "object",
        "description": "Information on an article including headline, url and main text",
        "x-examples": {
          "example": {
            "headline": "Listeriosis - Australia",
            "url": "https://www.who.int/csr/don/09-april-2018-listeriosis-australia/en/",
            "location": "Australia",
            "reports": [
              {
                "diseases": [
                  "Listeriosis"
                ],
                "syndromes": [],
                "event_date": "2018-04-06",
                "locations": [
                  "Australia"
                ]
              }
            ],
            "termFound": "Listeriosis",
            "main_text": "On 2 March 2018, the Australian National Focal Point (NFP) notified WHO of an outbreak of Listeria monocytogenes infection (listeriosis) associated with the consumption of rockmelons (cantaloupe) from a single grower. From 17 January 2018 through to 6 April 2018, 20 outbreak cases (19 confirmed and 1 probable) of listeriosis were reported. All of the cases were hospitalized and there have been seven deaths and one miscarriage associated with the outbreak. All of the outbreak cases have had illness onset since 17 January 2018. Public health response. Epidemiological investigations suggested that the source of the outbreak was rockmelon (cantaloupe melons) from a single grower in Australia. Epidemiological and environmental investigations were undertaken, which led to the recall of rockmelons produced by the single grower on 27 February 2018. On 1 March 2018, the Australian NFP was notified that international distribution of the affected product had occurred. Australian authorities received information from trace forward investigations on 2 March 2018 that the rockmelons from this grower were exported to eight countries; Hong Kong Special Administrative Region (China), Japan, Kuwait, Malaysia, Oman, Qatar, Singapore, and United Arab Emirates. The Australian NFP directly advised these countries on 3 March 2018 about the export of rockmelons from Australia to their country. In parallel, a notification via the International Food Safety Authorities Network (INFOSAN) was also sent on 3 March 2018.Further trace forward investigations on 7 March 2018 identified that Bahrain also received an export of the rockmelons from this grower and on 8 March 2018, investigations further identified that the affected rockmelons may have been included in a consignment to the Seychelles. The Australian NFP advised the Bahrain NFP directly on 8 March 2018 and the Seychelles NFP directly on 9 March 2018. As of 8 March, trace forward activities have been concluded.The INFOSAN emergency contact points in the importing countries were provided with specific distribution details of the rockmelons to their respective countries by the INFOSAN emergency contact point in Australia, as they became available. On 4 April 2018, it was reported that more than 30 samples of melons from the grower through the supply chain, including retail and on farm, tested positive to Listeria monocytogenes. Additional testing found L. monocytogenes in the packing area. All L. monocytogenes samples had the same genetic sequence as the human cases. It is believed that the cause of the outbreak was a combination of environmental conditions and weather contaminating the surface of the fruit, with low levels of the bacteria persisting after the washing process. The grower continues to work closely with the relevant authorities and has returned to supply rockmelons (during the week starting 2 April) after testing cleared the property. WHO risk assessment.The prompt epidemiological and environmental investigation carried out led to the identification of the outbreak source and enabled the issuing of a recall. Due to the potentially long incubation period of L. monocytogenes, further outbreak cases may be reported. Import details have been provided though INFOSAN to the affected countries to enable them to take appropriate management measures including local recalls and risk communication. Cases in the affected countries may still be identified.WHO advice. Pregnant women, the elderly and immunocompromised individuals should take precautions to avoid infection by Listeria by avoiding the consumption of high risk foods including dairy products made of unpasteurized milk, soft cheeses, deli meat products (ready-to eat meat cuts, pâté, etc.); ice creams, raw seafood, crustaceans, and shellfish. These are the most common foods associated with Listeria infection. In recent years, melon, and other fruits and vegetables have been implicated on rare occasions in outbreaks of listeriosis. To reduce the risk, it is important to thoroughly wash all fruits and vegetables. It is recommended that risk communication messages regarding listeriosis be targeted to at-risk groups, primarily pregnant women, older persons and people with weakened immune systems, for example people with cancer, HIV, diabetes, kidney or liver disease or those taking immunosuppressive medications. These messages should recommend avoiding the consumption of high-risk foods.",
            "date_of_publication": "2018-04-09"
          }
        },
        "properties": {
          "headline": {
            "description": "",
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "location": {
            "type": "string"
          },
          "reports": {
            "type": "array",
            "description": "",
            "items": {
              "$ref": "#/components/schemas/Report"
            }
          },
          "termFound": {
            "type": "string"
          },
          "main_text": {
            "type": "string"
          },
          "date_of_publication": {
            "$ref": "#/components/schemas/Dates"
          }
        },
        "required": [
          "headline",
          "url",
          "location",
          "reports"
        ]
      },
      "UserInput": {
        "title": "UserInput",
        "type": "object",
        "x-examples": {
          "FranceRequest": {
            "startDate": "2019-01-11T09:02:00",
            "endDate": "2020-01-01T11:02:10",
            "keyTerms": "yellow fever,ravies",
            "location": "France"
          }
        },
        "description": "Data the user can input",
        "properties": {
          "startDate": {
            "type": "string",
            "example": "YYYY-MM-DDTHH:MM:SS"
          },
          "endDate": {
            "type": "string",
            "example": "YYYY-MM-DDtHH:MM:SS"
          },
          "keyTerms": {
            "type": "string"
          },
          "location": {
            "type": "string"
          }
        }
      },
      "Report": {
        "title": "Report",
        "type": "object",
        "x-examples": {
          "Example": {
            "diseases": [
              "COVID",
              "Malaria"
            ],
            "syndromes": [],
            "event_date": "2019-05-05 11:22:01",
            "locations": [
              "Sydney",
              "Melbourne",
              "Perth"
            ]
          }
        },
        "properties": {
          "diseases": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Disease"
            }
          },
          "syndromes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Syndrome"
            }
          },
          "event_date": {
            "$ref": "#/components/schemas/Dates"
          },
          "locations": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Location"
            }
          }
        },
        "required": [
          "event_date"
        ],
        "description": "One case of diseases"
      },
      "Dates": {
        "title": "Dates",
        "oneOf": [
          {
            "$ref": "#/components/schemas/DateExact"
          },
          {
            "$ref": "#/components/schemas/DateRange"
          }
        ],
        "description": "Either in the form of a single date or a range",
        "x-examples": {
          "date range": "2018-11-01 17:xx:xx to 2018-12-xx xx:xx:xx",
          "date exact": "2015-10-01 xx:xx:xx"
        }
      },
      "DateRange": {
        "type": "string",
        "title": "DateRange",
        "pattern": "^(\\d{4})-(\\d\\d|xx)-(\\d\\d|xx) (\\d\\d|xx):(\\d\\d|xx):(\\d\\d|xx) to (\\d{4})-(\\d\\d|xx)-(\\d\\d|xx) (\\d\\d|xx):(\\d\\d|xx):(\\d\\d|xx)$",
        "description": "Date range",
        "x-examples": {
          "Example of date range": "2015-10-01 08:45:10 to 2016-10-01 08:45:10",
          "example-2": "2018-xx-xx xx:xx:xx to 2019-xx-xx xx:xx:xx",
          "example-3": "2018-11-01 17:xx:xx to 2018-12-xx xx:xx:xx"
        }
      },
      "DateExact": {
        "type": "string",
        "title": "DateExact",
        "x-examples": {
          "Example of single date": "2015-10-01 08:45:10"
        },
        "pattern": "^(\\d{4})-(\\d\\d|xx)-(\\d\\d|xx) (\\d\\d|xx):(\\d\\d|xx):(\\d\\d|xx)$",
        "description": "Single date"
      },
      "Disease": {
        "type": "string",
        "title": "Disease",
        "description": "Disease name",
        "x-examples": {
          "Coronavirus": "Coronavirus",
          "Malaria": "Malaria",
          "Measles": "Measles",
          "Tuberculosis": "Tuberculosis"
        },
        "enum": [
          "listeriosis",
          "yellow fever",
          "cholera",
          "haemorrhagic fever syndrome",
          "acute watery diarrhoeal syndrome",
          "leishmaniasis",
          "dengue fever",
          "influenza",
          "acute respiratory syndrome",
          "measles",
          "staphylococcal food intoxication",
          "lassa fever",
          "meningococcal disease",
          "leptospirosis",
          "rift valley fever",
          "middle east respiratory syndrome coronavirus (mers-cov)",
          "monkeypox",
          "ebola virus disease",
          "chikungunya",
          "gonococcal infection",
          "hantavirus pulmonary syndrome",
          "poliomyelitis",
          "hepatitis",
          "oropouche virus disease",
          "novel coronavirus",
          "typhoid fever",
          "nipah virus",
          "plague",
          "myocarditis",
          "anthrax",
          "rabies",
          "legionellosis",
          "enterovirus",
          "malaria",
          "crimean-congo haemorrhagic fever",
          "dengue haemorrhagic fever",
          "legionnaires",
          "west nile fever",
          "relapsing fever",
          "coccidioidomycosis",
          "acute neurological syndrome",
          "shigellosis",
          "marburg haemorrhagic fever",
          "japanese encephalitis",
          "botulism"
        ]
      },
      "Syndrome": {
        "title": "Syndrome",
        "type": "string",
        "description": "Syndrome name",
        "x-examples": {
          "Dry eye syndrome": "Dry eye syndrome",
          "Holt–Oram syndrome": "Holt–Oram syndrome"
        }
      },
      "Location": {
        "title": "Location",
        "type": "object",
        "description": "Country and location name e.g. state/city",
        "x-examples": {
          "example-1": {
            "country": "Australia",
            "location": "Sydney"
          },
          "example-2": {
            "country": "Australia",
            "location": "New South Wales"
          }
        },
        "properties": {
          "country": {
            "type": "string"
          },
          "location": {
            "type": "string"
          }
        }
      },
      "EventType": {
        "title": "EventType",
        "type": "string",
        "description": "'presence', 'death', 'infected', 'hospitalised', 'recovered', ''",
        "x-examples": {
          "presence": "presence",
          "death": "death",
          "infected": "indected",
          "hospitalised": "hospitalised",
          "recovered": "recovered",
          "empty": ""
        }
      },
      "DebugInfo": {
        "title": "DebugInfo",
        "type": "object",
        "description": "Additional information",
        "x-examples": {
          "example-1": {
            "name": "KoolKats",
            "accessTime": 0,
            "serviceTime": 0,
            "dataSource": "WHO"
          }
        },
        "properties": {
          "name": {
            "type": "string",
            "default": "KoolKats",
            "readOnly": true
          },
          "accessTime": {
            "type": "string"
          },
          "serviceTime": {
            "type": "string"
          },
          "dataSource": {
            "type": "string",
            "default": "WHO",
            "readOnly": true
          }
        }
      },
      "Occurrences": {
        "title": "Occurrences",
        "type": "object",
        "description": "Name of disease/location and occurence of disease",
        "properties": {
          "name": {
            "type": "string"
          },
          "occurrences": {
            "type": "integer"
          }
        },
        "x-examples": {
          "15 different diseases occur in Australia": {
            "name": "Australia",
            "occurrences": 15
          },
          "COVID-19 occurs in 30 countries": {
            "name": "COVID-19",
            "occurrences": 30
          }
        }
      }
    },
    "responses": {
      "ArticleList": {
        "description": "List of articles",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "articles": {
                  "$ref": "#/components/schemas/Article"
                },
                "debugInfo": {
                  "$ref": "#/components/schemas/DebugInfo"
                }
              },
              "required": [
                "articles"
              ]
            }
          }
        }
      }
    },
    "parameters": {
      "numDiseases": {
        "name": "numDiseases",
        "in": "query",
        "schema": {
          "type": "integer",
          "default": "10"
        },
        "description": "Limits the number of disease object you get in the response, default is 10."
      }
    },
    "securitySchemes": {}
  }
}
